export const FETCH_LAWYER_DETAILS_REQUEST = "FETCH_LAWYER_DETAILS_REQUEST";
export const FETCH_LAWYER_DETAILS_SUCCESS = "FETCH_LAWYER_DETAILS_SUCCESS";
export const FETCH_LAWYER_DTAILS_FAILED = "FETCH_LAWYER_DTAILS_FAILED";

export const BOOK_APPOINTMENT_REQUEST = "BOOK_APPOINTMENT_REQUEST";
export const BOOK_APPOINTMENT_SUCCESS = "BOOK_APPOINTMENT_SUCCESS";
export const BOOK_APPOINTMENT_FAILED = "BOOK_APPOINTMENT_FAILED";
